apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-config
  labels:
    app: agent
    component: config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
